[package]
name = "opentelemetry"
version = "0.1.0"
authors = ["Julian Tescher <julian@tescher.me>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
crossbeam-channel = "0.3.9"
rustracing = "0.2.0"
rustracing_jaeger = "0.2.1"
